# Base Image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy app files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source files
COPY . .

# Build app and prune dev dependencies
RUN npm run build && \ 
    npm prune --production

# Expose port
EXPOSE 3000

# Start client
CMD ["npm", "start"]