apiVersion: v1
kind: Service
metadata:
  name: myapp-server
spec:
  type: LoadBalancer
  selector:
    app: myapp-server
  ports:
    - name: http
      port: 80
      targetPort: 5500
    - name: mongo
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-client
spec:
  type: LoadBalancer
  selector:
    app: myapp-client
  ports:
    - name: http
      port: 80
      targetPort: 3000